### ISSUE TITLE
tutorials <-> documentation

### ISSUE THREAD

**Issue by martinjaggi** [mlbench/mlbench-docs#18]
the two tutorials which are currently in the blog should also be in the documentation maybe? this way would be easier to keep them up to date.

and cross-link blog and tutorials

**Comment by giorgiosav** [comment]
The second tutorial should also be updated with the new backend functionality. I can take care of this.

**Comment by giorgiosav** [comment]
I guess the bigger question is whether tutorials should be transferred entirely to the documentation and removed from the blog. In the blog, the tutorials will become outdated eventually and it might be hard to find them among other posts.
