### ISSUE TITLE
Remove manual installation scripts

### ISSUE THREAD

**Issue by ehoelzl** [mlbench/mlbench-docs#30]
Related to [#19](https://github.com/mlbench/mlbench-helm/issues/19).

Since we now have a robust CLI, it is no longer very useful to have manual scripts for GCloud and helm charts.
Also, now that we have doc for using KIND, we can also remove minikube as it is not useful.

We thus need to remove parts of https://mlbench.readthedocs.io/en/latest/installation.html#manual-setup.

Those are of course open to discussion.

My idea was to keep the Automatic installation and the usage of KIND, and maybe add a helm deployment for other types of clusters (i.e. helm commands for chart deployment only)

**Comment by martinjaggi** [comment]
yes, can remove.
and best to mark the sections in the tutorial clearly as to which are
mandatory and which are optional

**Comment by ehoelzl** [comment]
I have updated the installation instructions and the prerequisites. They are reflected here https://mlbench.readthedocs.io (I built from my branch so nothing is lost).

Let me know if you need me to do additional changes to those pages. 

@mmilenkoski Could you double check the KIND tutorial and see if it works as expected ?

**Comment by mmilenkoski** [comment]
The instructions for KIND are good, but there appears to be an issue with the deprecated packages in Kubernetes 1.16 when installing with helm. It was working previously, but I can not identify the problem. Maybe something changed in kind in the meantime. I think it's best if we upgrade MLBench to the newest Kubernetes because it creates problems with AWS too. I can work on that.

**Comment by ehoelzl** [comment]
> The instructions for KIND are good, but there appears to be an issue with the deprecated packages in Kubernetes 1.16 when installing with helm. It was working previously, but I can not identify the problem. Maybe something changed in kind in the meantime. I think it's best if we upgrade MLBench to the newest Kubernetes because it creates problems with AWS too. I can work on that.

Might also come from new helm version. It would be nice if we updated kubernetes to 1.16 to have it working on both AWS and GCP.
