### ISSUE TITLE
Update Contributing Page

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench-docs#4]
The current Contributing page is still mostly untouched from the initially generated one that comes with the python cookiecutter project template and is out of date with how the project works right now (It assumes that mlbench is just a python package, as opposed to the multiple components we have now).

The Contributing page should be updated to reflect the current state of the project.

**Comment by Panaetius** [comment]
@LucianaMarques So far no one is assigned to this issue, so feel free to submit a PR later. Thanks a lot :)

**Comment by LucianaMarques** [comment]
> @LucianaMarques So far no one is assigned to this issue, so feel free to submit a PR later. Thanks a lot :)

I'll surely do it, thanks!

**Comment by LucianaMarques** [comment]
Just to detail what I intend to do: this weekend I'll talke a good look at everything (I just came across with the project on the web this week) and make the modifications based on my experience as a new willing contributor to the project!
